on: [workflow_dispatch]

env:
  ARTIFACT_NAME: session

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: create folder
      run: |
        mkdir -p /mnt/up

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: false
        sudo: true

    - name: Set artifact name
      run: echo "ARTIFACT_NAME=$(ls /mnt/up | head -n 1)" >> "$GITHUB_ENV"

    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: /mnt/up
        compression-level: 0