on: [workflow_dispatch]

env:
  ARTIFACT_NAME: session

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: false
    - uses: actions/upload-artifact@v4
      with:
        # echo "ARTIFACT_NAME=my-artifact" >> $GITHUB_ENV
        name: ${{ env.ARTIFACT_NAME }}
        path: /mnt/up
        compression-level: 0